// @ts-nocheck
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#620040',
        'outline': '#988d9f',
        'on-error': '#690005',
        'tertiary-fixed': '#ffd8e7',
        'on-primary-fixed': '#2c0051',
        'inverse-on-surface': '#283044',
        'inverse-surface': '#dae2fd',
        'secondary-fixed-dim': '#adc6ff',
        'on-background': '#dae2fd',
        'surface-container-high': '#222a3d',
        'on-secondary': '#002e6a',
        'tertiary-fixed-dim': '#ffafd3',
        'secondary-fixed': '#d8e2ff',
        'on-surface': '#dae2fd',
        'on-tertiary-fixed-variant': '#85145a',
        'surface': '#0b1326',
        'on-tertiary-container': '#560038',
        'surface-tint': '#ddb7ff',
        'on-tertiary-fixed': '#3d0026',
        'on-primary-container': '#400071',
        'on-secondary-container': '#e6ecff',
        'primary-fixed': '#f0dbff',
        'surface-container-low': '#131b2e',
        'secondary': '#adc6ff',
        'on-primary-fixed-variant': '#6900b3',
        'surface-variant': '#2d3449',
        'on-primary': '#490080',
        'error': '#ffb4ab',
        'tertiary-container': '#e364a7',
        'on-error-container': '#ffdad6',
        'background': '#0b1326',
        'primary-fixed-dim': '#ddb7ff',
        'outline-variant': '#4d4354',
        'surface-dim': '#0b1326',
        'tertiary': '#ffafd3',
        'secondary-container': '#0566d9',
        'surface-container-lowest': '#060e20',
        'on-secondary-fixed': '#001a42',
        'inverse-primary': '#842bd2',
        'surface-container': '#171f33',
        'surface-bright': '#31394d',
        'on-secondary-fixed-variant': '#004395',
        'primary': '#ddb7ff',
        'on-surface-variant': '#cfc2d6',
        'primary-container': '#b76dff',
        'error-container': '#93000a',
        'surface-container-highest': '#2d3449',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
};
